#!/bin/bash

while read file
do
    fullpath="$(pwd)/$file"
    case "$1" in
    "w")
    ln -sf $fullpath $HOME/.config/.wall &&
	sh "$HOME/.config/scripts/set-wallpaper.sh";;
	# cp "$file" ~/.config/.wall.png && 
    "r")
	convert -rotate 90 "$file" "$file";;
    "R")
	convert -rotate -90 "$file" "$file";;
    "d")
	rm "$file";;
    esac
done
