#!/bin/bash

script=$(find -L ~/.config/scripts -name "*.sh" | awk '
  function basename(file, a, n) {
    n = split(file, a, "/")
    return a[n]
  }
{print basename($1)} ' - | dmenu -l 15 -i -p "Choose a script to run:")

~/.config/scripts/$script
