# Use custom format
format = '''$all'''

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = true

[username]
show_always = true
style_user = 'blue'

[hostname]
ssh_only = false
style = 'white'

[directory]
style = 'white bold'
