#!/bin/bash

while read file
do
    fullpath="$(pwd)/file"
    case "$1" in
    "w")
	cp "$file" ~/.config/wall.png && 
	sh "$HOME/.config/scripts/set-wallpaper.sh";;
    "r")
	convert -rotate 90 "$file" "$file";;
    "R")
	convert -rotate -90 "$file" "$file";;
    "d")
	rm "$file";;
    esac
done
