#! /bin/sh

sxhkd &
compton &
#~/.config/lemonbar/run_lemonbar.sh &
~/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^10' follow=on
bspc rule -a telegram desktop='^7'
bspc rule -a Rambox desktop='^7'
bspc rule -a Discord desktop='^7'
bspc rule -a Signal desktop='^6'
bspc rule -a Screenkey manage=off

bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled

#bspc rule -a scratchpad sticky=on state=floating hidden=on
#st -c scratchpad -e ~/.config/scripts/scratch &
