#!/bin/bash

while read file
do
    fullpath="$(pwd)/$file"
    case "$1" in
    "w")
    echo "$fullpath" && ln -sf "$fullpath" "$HOME/.config/.wall";;
    "r")
	convert -rotate 90 "$file" "$file";;
    "R")
	convert -rotate -90 "$file" "$file";;
    "C-d")
        mv -vf "$file" /tmp;;
    "c")
        xclip-copyfile "$file";;
    esac
done
