#! /bin/sh

sxhkd &
compton &
#~/.config/lemonbar/run_lemonbar.sh &
polybar Bar&

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap		 8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Firefox desktop='^9' state=floating follow=on
bspc rule -a Telegram desktop='^7'
bspc rule -a Screenkey manage=off
